"""
Algo Trading Agent models.

TradingAgent — configuration for an autonomous trading agent
AgentLog     — timestamped log entries per agent
AgentTrade   — trades generated by an agent (pending, confirmed, executed, paper)
"""

from datetime import datetime, timezone

from sqlalchemy import (
    Boolean, Column, Integer, String, Float, DateTime, ForeignKey, JSON, Text,
)
from sqlalchemy.orm import relationship

from app.core.database import Base


class TradingAgent(Base):
    __tablename__ = "trading_agents"

    id = Column(Integer, primary_key=True, index=True)
    name = Column(String(100), nullable=False)
    strategy_id = Column(Integer, ForeignKey("strategies.id"), nullable=False)
    broker_name = Column(String(50), default="mt5")
    symbol = Column(String(20), nullable=False)
    timeframe = Column(String(10), nullable=False, default="M10")

    # Optional ML model for signal filtering/enhancement
    ml_model_id = Column(Integer, ForeignKey("ml_models.id"), nullable=True)

    # Agent mode: paper | confirmation | auto
    mode = Column(String(20), nullable=False, default="paper")

    # Status: stopped | running | paused | error
    status = Column(String(20), nullable=False, default="stopped")

    # Risk configuration
    risk_config = Column(JSON, default=dict)
    # { max_daily_loss_pct, max_open_positions, max_drawdown_pct,
    #   position_size_type, position_size_value, exposure_limit }

    # Performance stats (updated periodically)
    performance_stats = Column(JSON, default=dict)
    # { total_trades, wins, losses, total_pnl, max_drawdown, win_rate, ... }

    created_by = Column(Integer, ForeignKey("users.id"), nullable=False)
    created_at = Column(DateTime, default=lambda: datetime.now(timezone.utc))
    updated_at = Column(DateTime, default=lambda: datetime.now(timezone.utc),
                        onupdate=lambda: datetime.now(timezone.utc))

    # Relationships
    strategy = relationship("Strategy")
    ml_model = relationship("MLModel", foreign_keys=[ml_model_id])
    creator = relationship("User")
    logs = relationship("AgentLog", back_populates="agent", cascade="all, delete-orphan")
    trades = relationship("AgentTrade", back_populates="agent", cascade="all, delete-orphan")


class AgentLog(Base):
    __tablename__ = "agent_logs"

    id = Column(Integer, primary_key=True, index=True)
    agent_id = Column(Integer, ForeignKey("trading_agents.id"), nullable=False)

    # Level: info | warn | error | trade | signal
    level = Column(String(10), nullable=False, default="info")
    message = Column(Text, nullable=False)
    data = Column(JSON, default=dict)

    created_at = Column(DateTime, default=lambda: datetime.now(timezone.utc))

    agent = relationship("TradingAgent", back_populates="logs")


class AgentTrade(Base):
    __tablename__ = "agent_trades"

    id = Column(Integer, primary_key=True, index=True)
    agent_id = Column(Integer, ForeignKey("trading_agents.id"), nullable=False)

    symbol = Column(String(20), nullable=False)
    direction = Column(String(10), nullable=False)  # BUY or SELL
    entry_price = Column(Float)
    exit_price = Column(Float)
    lot_size = Column(Float, default=0.01)
    stop_loss = Column(Float)
    take_profit_1 = Column(Float)
    take_profit_2 = Column(Float)

    pnl = Column(Float, default=0.0)
    pnl_pct = Column(Float, default=0.0)

    # Status: pending_confirmation | confirmed | executed | rejected | paper | closed
    status = Column(String(30), nullable=False, default="pending_confirmation")

    # Signal metadata
    signal_type = Column(String(20))       # BOS, CHoCH, etc.
    signal_reason = Column(Text)
    signal_confidence = Column(Float, default=0.0)

    broker_ticket = Column(String(50))     # Broker order ID when executed

    opened_at = Column(DateTime, default=lambda: datetime.now(timezone.utc))
    closed_at = Column(DateTime)
    created_at = Column(DateTime, default=lambda: datetime.now(timezone.utc))

    agent = relationship("TradingAgent", back_populates="trades")
